services:
  - type: cron
    name: bot-maioca-status
    runtime: python
    repo: https://github.com/superafisca/bot-maioca-status
    schedule: "*/30 * * * *"
    buildCommand: |
      apt-get update && apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: "python automação_maioca_loja_nova.py"
    workingDirectory: .
